language: ruby
rvm:
  - "2.3.1"

addons:
  postgresql: "9.5.4"

script: "RAILS_ENV=test bundle exec rake"

before_script:
  - sudo service postgresql start
  - cd pesquini/
  - gem install rspec rspec-rails simplecov
  - bundle install
  - psql -c 'create database pesquini_test;' -U postgres;
  - psql -c 'create user pesquini;' -U postgres;
  - rake db:setup

bundler_args: --binstubs=./bundler_stubs

sudo: required

notifications:
  email:
    recipients:
      - adailson2@gmail.com
